"""empty message

Revision ID: d74e0da0fca2
Revises: 2c80b8d58b28
Create Date: 2019-05-21 09:46:55.215030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74e0da0fca2'
down_revision = '2c80b8d58b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('planned_month_deposit', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'planned_month_deposit')
    # ### end Alembic commands ###
